# Host list
# "name" is mandatory and will be used as target to connect
# "title" will be displayed as "human name" instead of "name" if specified
# All defaults values can be overriden per host basis
hosts:
  - name: toxicdev.me
    title: Main Site
  - name: help.toxicdev.me
    title: Docs Site
  - name: source.toxicdev.me
    title: My Code Bin
  - name: api.toxicdev.me
    title: My API

# Site configuration
site:
  # Title
  title: Toxic Response Time
  # Favicon / logo
  favicon: https://beta.diswidgets.org/logo.png
  # Refresh rate of status images for client
  refresh_rate_sec: 120

# Default values
defaults:
  # Default command to use
  # Supported values are :
  # - "curl"   [supports both uptime and response time, but only for HTTP/S requests]
  # - "ncat"   [supports both uptime and response time]
  # - "telnet" [supports only uptime]
  use: curl
  # Default timeout
  timeout: 30
  # Default port
  port: 443
  # Default number of ms before considering that host have latency problems
  status_slow_ms: 30000
